### ISSUE TITLE
How make it working with firefox bookmarks?

### ISSUE THREAD

**Issue by natanielcz** [bmh1980/gnome-shell-extension-searchbookmarks#1]
Hi,
Can you explain me what have i do to make it working with firefox browser? I don't know what are GIR files and how to install it. I can't find it in software center.

**Comment by bmh1980** [comment]
You can find it in the software center, if you enter 'gir1.2-gda-5.0'
into the search field. Or you install it via apt-get from a terminal
with the command 'sudo apt-get install gir1.2-gda-5.0'.

Greetings
Marcus

Am 01.02.2013 23:59, schrieb natanielcz:
