### ISSUE TITLE
Update to staging ppa broke it

### ISSUE THREAD

**Issue by mightymouse2045** [bmh1980/gnome-shell-extension-searchbookmarks#8]
(this is for gnome-shell 3.10.1)

Hi again - sorry I updated to staging ppa to test something else and it broke the extension with this:

(gnome-shell:9418): Gjs-WARNING **: JS ERROR: Exception in callback for signal: search-updated: TypeError: this.provider.filterResults is not a function
SearchResultsBase<.updateSearch@/usr/share/gnome-shell/js/ui/searchDisplay.js:233
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchResults<._updateResults@/usr/share/gnome-shell/js/ui/searchDisplay.js:504
wrapper@/usr/share/gjs-1.0/lang.js:213
_emit@/usr/share/gjs-1.0/signals.js:124
SearchSystem<.setResults@/usr/share/gnome-shell/js/ui/search.js:60
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchBookmarks<.getInitialResultSet@/home/ph/.local/share/gnome-shell/extensions/searchbookmarks@bmh1980de.gmail.com/extension.js:176
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchBookmarks<.getSubsearchResultSet@/home/ph/.local/share/gnome-shell/extensions/searchbookmarks@bmh1980de.gmail.com/extension.js:183
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchSystem<.updateSearchResults@/usr/share/gnome-shell/js/ui/search.js:87
wrapper@/usr/share/gjs-1.0/lang.js:213
ViewSelector<._doSearch@/usr/share/gnome-shell/js/ui/viewSelector.js:489
wrapper@/usr/share/gjs-1.0/lang.js:213

**Comment by mightymouse2045** [comment]
bump :P

**Comment by bmh1980** [comment]
Can you please test the modifications before I’m tagging a new version?

**Comment by mightymouse2045** [comment]
I just switched over to Fedora and trying it now - I get this error now though:

Gjs-Message: JS LOG: ERROR: No provider 'SQLite' installed

**Comment by bmh1980** [comment]
I think you have to install the libgda-sqlite package from the repo.

**Comment by mightymouse2045** [comment]
works nicely now - thanks :) One thing I noticed is if I rename a bookmark it still shows as the old name until I restart the shell. But apart from that it works very well :)
